Add pt agent which throws strange circularity err
This prototype Java agent creates a `ClassCircularityError` when I run
its test, `@pt_asm_java_agent//pt/jvm/classcircularityerror:test`, but I
don't yet understand why. The test log includes a bunch of these lines:

```
java.lang.ClassCircularityError: java/lang/invoke/StringConcatFactory
```

According to its Javadoc, a `ClassCircularityError` indicates that "the
Java Virtual Machine detects a circularity in the superclass hierarchy
of a class being loaded". I have no idea how my code could be causing
such a problem since *my code is not modifying any bytecode*.

Skimming the Javadoc for `StringConcatFactory`, I don't really
understand what it does. There seems to be some black magic going on
here for *creating* string concatenation methods.

I seem to be able to sidestep this error by either commenting out bits
of `MyAgent.java`, e.g.,

- the use of ASM code on lines 24-25.
- the string concatenation on line 42.

For now, I'm just keeping this around in case I run into more of these
errors and I need to actually understand this problem.

It would be nice to create a more minimal example, but I'm not taking
the time to do so right now.

Who knows, maybe this is an obscure JVM bug.