Draft JVMTI agent: instr app monitor instructions
This drafts a JVMTI agent in Rust. Its functionality is similar to the
test Java agent (i.e. `//phasicj/agent/instr/test/java_agent`), but this
functionality is deployed quite differently. `//phasicj/agent:INDEX.md`
describes the design.

There is still one unfortunate functional difference between this JVMTI
agent and the test Java agent: instrumentation is not performed on any
classes whose package paths begin with `java`, `sun`, or `jdk`.
Instrumenting some of these classes causes `NoClassDefFoundError`s when
they try to call the PhasicJ runtime. I haven't yet figured out why.