Forward agent events through `java.lang.Object`
Instrumentation sites now call static event handler methods on
`java.lang.Object`. These events are "forwarded" to the runtime,
specifically, `phasicj.agent.rt.ApplicationEvents`. Events are only
forwarded after the VMStart event occurs. (Before this event, they are
dropped.)

This event forwarding strategy is my solution to crashes caused by
instrumenting classes in the `java.base` module during the primordial
phase. During this phase,

- The JVM's initialization process has not yet reached the point that
  it can load classes outside of `java.base`.
- The JVM executes some of my instrumented code.

Thus, I can't just add instrumented static method calls from these
`java.base` classes to my `ApplicationEvents` class. It causes
`NoClassDefFoundError`s even though this class is available on the boot
class path. I use `Object` as an intermediary for events because it is
in the `java.base` module. (I believe that I could have used any class
in `java.base` to forward these events. My choice of of `Object` was
arbitrary.)

The fields & methods to be added to the `Object` class are encoded in
the `JavaLangObjectAmendment` class.